Add docker/machine

diff --git a/zsh/.zsh/rc b/zsh/.zsh/rc
--- a/zsh/.zsh/rc
+++ b/zsh/.zsh/rc
@@ -73,25 +73,25 @@ fi
 
 function mkcd(){mkdir -p $1 && cd $1}
 
-case ${OSTYPE} in
-  darwin*)
-    # VBoxManage startvm --type headless boot2docker-vm // if fail
-    $(boot2docker shellinit)
-
-    boot2docker status
-    if [ $? -ne 0 ]; then
-      # VBoxManage sharedfolder add boot2docker-vm -name home -hostpath $HOME
-      boot2docker up
-    #   # boot2docker ssh "sudo modprobe vboxsf && mkdir -p $HOME && sudo mount -t vboxsf home $HOME"
-    #   boot2docker ssh "sudo modprobe vboxsf && mkdir -p /home/ec2-user && sudo mount -t vboxsf home /home/ec2-user"
-    else
-      echo "boot2docker is already running. Execute this manuallly:"
-      echo 'boot2docker ssh "sudo modprobe vboxsf && mkdir -p $HOME && sudo mount -t vboxsf home $HOME"'
-    fi
-    ;;
-  linux*)
-    ;;
-esac
+# case ${OSTYPE} in
+#   darwin*)
+#     # VBoxManage startvm --type headless boot2docker-vm // if fail
+#     $(boot2docker shellinit)
+#
+#     boot2docker status
+#     if [ $? -ne 0 ]; then
+#       # VBoxManage sharedfolder add boot2docker-vm -name home -hostpath $HOME
+#       boot2docker up
+#     #   # boot2docker ssh "sudo modprobe vboxsf && mkdir -p $HOME && sudo mount -t vboxsf home $HOME"
+#     #   boot2docker ssh "sudo modprobe vboxsf && mkdir -p /home/ec2-user && sudo mount -t vboxsf home /home/ec2-user"
+#     else
+#       echo "boot2docker is already running. Execute this manuallly:"
+#       echo 'boot2docker ssh "sudo modprobe vboxsf && mkdir -p $HOME && sudo mount -t vboxsf home $HOME"'
+#     fi
+#     ;;
+#   linux*)
+#     ;;
+# esac
 
 eval "$(direnv hook zsh)"
 
